name: Build and Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-and-release:
    name: Build and Release for Windows
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc
      
      - name: Build for Windows (AMD64)
        run: |
          cargo build --release --target x86_64-pc-windows-msvc
      
      - name: Prepare artifacts
        run: |
          mkdir -p ./artifacts
          cp target/x86_64-pc-windows-msvc/release/manyacg-wallpaper.exe ./artifacts/
          cp README.md ./artifacts/ || echo "No README.md found"
          cp LICENSE ./artifacts/ || echo "No LICENSE found"
        shell: bash
      
      - name: Create ZIP archive
        run: |
          cd artifacts
          7z a ../manyacg-wallpaper-windows-amd64.zip *
        shell: bash
      
      - name: Get the version
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
        shell: bash
      
      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          name: manyacg-wallpaper ${{ steps.get_version.outputs.VERSION }}
          files: manyacg-wallpaper-windows-amd64.zip
          generate_release_notes: true