name: Build and Release

on:
  push:
    tags:
      - 'v*'  # 当推送带v前缀的标签时触发，例如v1.0.0

jobs:
  build-and-release:
    name: Build and Release
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          
      - name: Build for Windows
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
          
      - name: Create release package
        run: |
          mkdir release-package
          cp target/release/manyacg-wallpaper.exe release-package/
          cp README.md release-package/ || echo "No README.md found"
          cd release-package
          7z a -tzip ../manyacg-wallpaper-windows.zip *
        shell: pwsh
        
      - name: Get tag name
        id: get_tag
        run: |
          echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
        shell: bash
        
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          name: ManyACG Wallpaper ${{ steps.get_tag.outputs.TAG_NAME }}
          draft: false
          prerelease: false
          files: manyacg-wallpaper-windows.zip
          body: |
            # ManyACG Wallpaper ${{ steps.get_tag.outputs.TAG_NAME }}
            
            自动从API获取壁纸并设置为Windows桌面背景的工具。
            
            ## 功能
            
            - 每日自动更换壁纸
            - 开机自启动
            - 自动清理旧壁纸
            
            ## 安装说明
            
            1. 下载并解压 `manyacg-wallpaper-windows.zip`
            2. 运行 `wallpaper_changer.exe`
            3. 程序将自动设置为开机启动
            
            ## 如何关闭自启动
            
            可以通过Windows任务管理器的"启动"选项卡或Windows设置中的"启动应用"来禁用。